### ISSUE TITLE
 $DBObject masks earlier declaration in same scope

### ISSUE THREAD

**Issue by NeverMin** [znuny/Znuny4OTRS-EscalationSuspend#7]
[Wed Feb  4 13:10:30 2015] Znuny4OTRSEscalationSuspend.pm: "my" variable $DBObject masks earlier declaration in same scope at /opt/otrs//Kernel/System/Ticket/Znuny4OTRSEscalationSuspend.pm line 380.

**Comment by hanneshal** [comment]
Fixed it, thx. :+1: 
The package wasn't released yet, I also did this right away.

**Comment by NeverMin** [comment]
good for me. thank you!

2015-02-04 14:54 GMT+08:00 Johannes Nickel <notifications@github.com>:
